version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: securePassword
      POSTGRES_USER: spield
      POSTGRES_DB: spield
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    volumes:
        - rmq-etc:/etc/rabbitmq/
        - rmq-data:/var/lib/rabbitmq/
        - rmq-logs:/var/log/rabbitmq/
    # Username/Password: guest/guest
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  db-data:
  rmq-etc:
  rmq-data:
  rmq-logs:
